// ======================================================================
// \title  BitfieldTestAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for BitfieldTest struct
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "BitfieldTestAc.hpp"

// ----------------------------------------------------------------------
// Constructors
// ----------------------------------------------------------------------

BitfieldTest ::
  BitfieldTest() :
    Serializable(),
    m_flags_enabled(0),
    m_flags_mode(0),
    m_flags_reserved(0),
    m_status_state(0),
    m_status_error(0),
    m_status_code(0),
    m_data(0)
{

}

BitfieldTest ::
  BitfieldTest(const BitfieldTest& obj) :
    Serializable(),
    m_flags_enabled(obj.m_flags_enabled),
    m_flags_mode(obj.m_flags_mode),
    m_flags_reserved(obj.m_flags_reserved),
    m_status_state(obj.m_status_state),
    m_status_error(obj.m_status_error),
    m_status_code(obj.m_status_code),
    m_data(obj.m_data)
{

}

// ----------------------------------------------------------------------
// Operators
// ----------------------------------------------------------------------

BitfieldTest& BitfieldTest ::
  operator=(const BitfieldTest& obj)
{
  if (this == &obj) {
    return *this;
  }

  set(obj.m_data);
  this->m_flags_enabled = obj.m_flags_enabled;
  this->m_flags_mode = obj.m_flags_mode;
  this->m_flags_reserved = obj.m_flags_reserved;
  this->m_status_state = obj.m_status_state;
  this->m_status_error = obj.m_status_error;
  this->m_status_code = obj.m_status_code;
  return *this;
}

bool BitfieldTest ::
  operator==(const BitfieldTest& obj) const
{
  return (
    (this->m_flags_enabled == obj.m_flags_enabled) &&
    (this->m_flags_mode == obj.m_flags_mode) &&
    (this->m_flags_reserved == obj.m_flags_reserved) &&
    (this->m_status_state == obj.m_status_state) &&
    (this->m_status_error == obj.m_status_error) &&
    (this->m_status_code == obj.m_status_code) &&
    (this->m_data == obj.m_data)
  );
}

bool BitfieldTest ::
  operator!=(const BitfieldTest& obj) const
{
  return !(*this == obj);
}

// ----------------------------------------------------------------------
// Member functions
// ----------------------------------------------------------------------

Fw::SerializeStatus BitfieldTest ::
  serializeTo(Fw::SerializeBufferBase& buffer, Fw::Serialization::Endianness mode) const
{
  Fw::SerializeStatus status;

  U8 packed_flags = 0;

  packed_flags |= (this->m_flags_enabled & 0x1) << 0;

  packed_flags |= (this->m_flags_mode & 0x3) << 1;

  packed_flags |= (this->m_flags_reserved & 0x1f) << 3;
  status = buffer.serializeFrom(packed_flags, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  U16 packed_status = 0;

  packed_status |= (this->m_status_state & 0xf) << 0;

  packed_status |= (this->m_status_error & 0xf) << 4;

  packed_status |= (this->m_status_code & 0xff) << 8;
  status = buffer.serializeFrom(packed_status, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  status = buffer.serializeFrom(this->m_data, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  return status;
}

Fw::SerializeStatus BitfieldTest ::
  deserializeFrom(Fw::SerializeBufferBase& buffer, Fw::Serialization::Endianness mode)
{
  Fw::SerializeStatus status;

  U8 packed_flags;
  status = buffer.deserializeTo(packed_flags, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  this->m_flags_enabled = (packed_flags >> 0) & 0x1;

  this->m_flags_mode = (packed_flags >> 1) & 0x3;

  this->m_flags_reserved = (packed_flags >> 3) & 0x1f;

  U16 packed_status;
  status = buffer.deserializeTo(packed_status, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  this->m_status_state = (packed_status >> 0) & 0xf;

  this->m_status_error = (packed_status >> 4) & 0xf;

  this->m_status_code = (packed_status >> 8) & 0xff;

  status = buffer.deserializeTo(this->m_data, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  return status;
}

#if FW_SERIALIZABLE_TO_STRING

void BitfieldTest ::
  toString(Fw::StringBase& sb) const
{
  Fw::String tmp;
  sb = "( ";
  tmp.format("%hhu", this->m_flags_enabled);
  sb += tmp;
  sb += ", ";
  tmp.format("%hhu", this->m_flags_mode);
  sb += tmp;
  sb += ", ";
  tmp.format("%hhu", this->m_flags_reserved);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_status_state);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_status_error);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_status_code);
  sb += tmp;
  sb += ", ";
  tmp.format("%u", this->m_data);
  sb += tmp;
  sb += " )";
}

#endif

// ----------------------------------------------------------------------
// Setter functions
// ----------------------------------------------------------------------

void BitfieldTest ::
  set_flags_enabled(U8 value)
{
  this->m_flags_enabled = value & 0x1;
}

void BitfieldTest ::
  set_flags_mode(U8 value)
{
  this->m_flags_mode = value & 0x3;
}

void BitfieldTest ::
  set_flags_reserved(U8 value)
{
  this->m_flags_reserved = value & 0x1f;
}

void BitfieldTest ::
  set_status_state(U16 value)
{
  this->m_status_state = value & 0xf;
}

void BitfieldTest ::
  set_status_error(U16 value)
{
  this->m_status_error = value & 0xf;
}

void BitfieldTest ::
  set_status_code(U16 value)
{
  this->m_status_code = value & 0xff;
}

void BitfieldTest ::
  set_data(U32 data)
{
  this->m_data = data;
}

void BitfieldTest ::
  set(U32 data)
{
  this->m_data = data;
}
