// ======================================================================
// \title  BitfieldTestAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for BitfieldTest struct
// ======================================================================

#ifndef BitfieldTestAc_HPP
#define BitfieldTestAc_HPP

#include "Fw/Types/Serializable.hpp"

//! Test struct with bitfield members
class BitfieldTest :
  public Fw::Serializable
{

  public:

    // ----------------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------------

    enum {
      //! The size of the serial representation
      SERIALIZED_SIZE =
        sizeof(U8) +
        sizeof(U16) +
        sizeof(U32)
    };

  public:

    // ----------------------------------------------------------------------
    // Constructors
    // ----------------------------------------------------------------------

    //! Constructor (default value)
    BitfieldTest();

    //! Copy constructor
    BitfieldTest(
        const BitfieldTest& obj //!< The source object
    );

  public:

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    //! Copy assignment operator
    BitfieldTest& operator=(
        const BitfieldTest& obj //!< The source object
    );

    //! Equality operator
    bool operator==(
        const BitfieldTest& obj //!< The other object
    ) const;

    //! Inequality operator
    bool operator!=(
        const BitfieldTest& obj //!< The other object
    ) const;

  public:

    // ----------------------------------------------------------------------
    // Member functions
    // ----------------------------------------------------------------------

    //! Serialization
    Fw::SerializeStatus serializeTo(
        Fw::SerializeBufferBase& buffer //!< The serial buffer
        , Fw::Serialization::Endianness mode = Fw::Serialization::BIG //!< Endianness of serialized buffer
    ) const;

    //! Deserialization
    Fw::SerializeStatus deserializeFrom(
        Fw::SerializeBufferBase& buffer //!< The serial buffer
        , Fw::Serialization::Endianness mode = Fw::Serialization::BIG //!< Endianness of serialized buffer
    );

#if FW_SERIALIZABLE_TO_STRING

    //! Convert struct to string
    void toString(
        Fw::StringBase& sb //!< The StringBase object to hold the result
    ) const;

#endif

    // ----------------------------------------------------------------------
    // Getter functions
    // ----------------------------------------------------------------------

    //! Get bitfield sub-field flags_enabled
    U8 get_flags_enabled() const
    {
      return this->m_flags_enabled;
    }

    //! Get bitfield sub-field flags_mode
    U8 get_flags_mode() const
    {
      return this->m_flags_mode;
    }

    //! Get bitfield sub-field flags_reserved
    U8 get_flags_reserved() const
    {
      return this->m_flags_reserved;
    }

    //! Get bitfield sub-field status_state
    U16 get_status_state() const
    {
      return this->m_status_state;
    }

    //! Get bitfield sub-field status_error
    U16 get_status_error() const
    {
      return this->m_status_error;
    }

    //! Get bitfield sub-field status_code
    U16 get_status_code() const
    {
      return this->m_status_code;
    }

    //! Get member data
    U32 get_data() const
    {
      return this->m_data;
    }

    // ----------------------------------------------------------------------
    // Setter functions
    // ----------------------------------------------------------------------

    //! Set bitfield sub-field flags_enabled
    void set_flags_enabled(
        U8 value
    );

    //! Set bitfield sub-field flags_mode
    void set_flags_mode(
        U8 value
    );

    //! Set bitfield sub-field flags_reserved
    void set_flags_reserved(
        U8 value
    );

    //! Set bitfield sub-field status_state
    void set_status_state(
        U16 value
    );

    //! Set bitfield sub-field status_error
    void set_status_error(
        U16 value
    );

    //! Set bitfield sub-field status_code
    void set_status_code(
        U16 value
    );

    //! Set member data
    void set_data(
        U32 data
    );

    //! Set all non-bitfield members
    void set(
        U32 data
    );

  protected:

    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! Bitfield sub-field enabled (1 bit)
    U8 m_flags_enabled;

    //! Bitfield sub-field mode (2 bits)
    U8 m_flags_mode;

    //! Bitfield sub-field reserved (5 bits)
    U8 m_flags_reserved;

    //! Bitfield sub-field state (4 bits)
    U16 m_status_state;

    //! Bitfield sub-field error (4 bits)
    U16 m_status_error;

    //! Bitfield sub-field code (8 bits)
    U16 m_status_code;

    U32 m_data;

};

#endif
