// ======================================================================
// \title  MixedStructAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for MixedStruct struct
// ======================================================================

#ifndef MixedStructAc_HPP
#define MixedStructAc_HPP

#include "Fw/Types/Serializable.hpp"

//! Struct with mixed bitfield and regular members
class MixedStruct :
  public Fw::Serializable
{

  public:

    // ----------------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------------

    enum {
      //! The size of the serial representation
      SERIALIZED_SIZE =
        sizeof(U8) +
        sizeof(U16) +
        sizeof(U16) +
        sizeof(F32)
    };

  public:

    // ----------------------------------------------------------------------
    // Constructors
    // ----------------------------------------------------------------------

    //! Constructor (default value)
    MixedStruct();

    //! Copy constructor
    MixedStruct(
        const MixedStruct& obj //!< The source object
    );

  public:

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    //! Copy assignment operator
    MixedStruct& operator=(
        const MixedStruct& obj //!< The source object
    );

    //! Equality operator
    bool operator==(
        const MixedStruct& obj //!< The other object
    ) const;

    //! Inequality operator
    bool operator!=(
        const MixedStruct& obj //!< The other object
    ) const;

  public:

    // ----------------------------------------------------------------------
    // Member functions
    // ----------------------------------------------------------------------

    //! Serialization
    Fw::SerializeStatus serializeTo(
        Fw::SerializeBufferBase& buffer //!< The serial buffer
        , Fw::Serialization::Endianness mode = Fw::Serialization::BIG //!< Endianness of serialized buffer
    ) const;

    //! Deserialization
    Fw::SerializeStatus deserializeFrom(
        Fw::SerializeBufferBase& buffer //!< The serial buffer
        , Fw::Serialization::Endianness mode = Fw::Serialization::BIG //!< Endianness of serialized buffer
    );

#if FW_SERIALIZABLE_TO_STRING

    //! Convert struct to string
    void toString(
        Fw::StringBase& sb //!< The StringBase object to hold the result
    ) const;

#endif

    // ----------------------------------------------------------------------
    // Getter functions
    // ----------------------------------------------------------------------

    //! Get bitfield sub-field header_version
    U8 get_header_version() const
    {
      return this->m_header_version;
    }

    //! Get bitfield sub-field header_type
    U8 get_header_type() const
    {
      return this->m_header_type;
    }

    //! Get bitfield sub-field header_valid
    U8 get_header_valid() const
    {
      return this->m_header_valid;
    }

    //! Get bitfield sub-field header_spare
    U8 get_header_spare() const
    {
      return this->m_header_spare;
    }

    //! Get member counter
    U16 get_counter() const
    {
      return this->m_counter;
    }

    //! Get bitfield sub-field control_enable
    U16 get_control_enable() const
    {
      return this->m_control_enable;
    }

    //! Get bitfield sub-field control_mode
    U16 get_control_mode() const
    {
      return this->m_control_mode;
    }

    //! Get bitfield sub-field control_priority
    U16 get_control_priority() const
    {
      return this->m_control_priority;
    }

    //! Get bitfield sub-field control_reserved
    U16 get_control_reserved() const
    {
      return this->m_control_reserved;
    }

    //! Get member value
    F32 get_value() const
    {
      return this->m_value;
    }

    // ----------------------------------------------------------------------
    // Setter functions
    // ----------------------------------------------------------------------

    //! Set bitfield sub-field header_version
    void set_header_version(
        U8 value
    );

    //! Set bitfield sub-field header_type
    void set_header_type(
        U8 value
    );

    //! Set bitfield sub-field header_valid
    void set_header_valid(
        U8 value
    );

    //! Set bitfield sub-field header_spare
    void set_header_spare(
        U8 value
    );

    //! Set member counter
    void set_counter(
        U16 counter
    );

    //! Set bitfield sub-field control_enable
    void set_control_enable(
        U16 value
    );

    //! Set bitfield sub-field control_mode
    void set_control_mode(
        U16 value
    );

    //! Set bitfield sub-field control_priority
    void set_control_priority(
        U16 value
    );

    //! Set bitfield sub-field control_reserved
    void set_control_reserved(
        U16 value
    );

    //! Set member value
    void set_value(
        F32 value
    );

    //! Set all non-bitfield members
    void set(
        U16 counter,
        F32 value
    );

  protected:

    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! Bitfield sub-field version (3 bits)
    U8 m_header_version;

    //! Bitfield sub-field type (3 bits)
    U8 m_header_type;

    //! Bitfield sub-field valid (1 bit)
    U8 m_header_valid;

    //! Bitfield sub-field spare (1 bit)
    U8 m_header_spare;

    U16 m_counter;

    //! Bitfield sub-field enable (1 bit)
    U16 m_control_enable;

    //! Bitfield sub-field mode (3 bits)
    U16 m_control_mode;

    //! Bitfield sub-field priority (4 bits)
    U16 m_control_priority;

    //! Bitfield sub-field reserved (8 bits)
    U16 m_control_reserved;

    F32 m_value;

};

#endif
