// ======================================================================
// \title  MixedStructAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for MixedStruct struct
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "MixedStructAc.hpp"

// ----------------------------------------------------------------------
// Constructors
// ----------------------------------------------------------------------

MixedStruct ::
  MixedStruct() :
    Serializable(),
    m_header_version(0),
    m_header_type(0),
    m_header_valid(0),
    m_header_spare(0),
    m_counter(0),
    m_control_enable(0),
    m_control_mode(0),
    m_control_priority(0),
    m_control_reserved(0),
    m_value(0.0)
{

}

MixedStruct ::
  MixedStruct(const MixedStruct& obj) :
    Serializable(),
    m_header_version(obj.m_header_version),
    m_header_type(obj.m_header_type),
    m_header_valid(obj.m_header_valid),
    m_header_spare(obj.m_header_spare),
    m_counter(obj.m_counter),
    m_control_enable(obj.m_control_enable),
    m_control_mode(obj.m_control_mode),
    m_control_priority(obj.m_control_priority),
    m_control_reserved(obj.m_control_reserved),
    m_value(obj.m_value)
{

}

// ----------------------------------------------------------------------
// Operators
// ----------------------------------------------------------------------

MixedStruct& MixedStruct ::
  operator=(const MixedStruct& obj)
{
  if (this == &obj) {
    return *this;
  }

  set(obj.m_counter, obj.m_value);
  this->m_header_version = obj.m_header_version;
  this->m_header_type = obj.m_header_type;
  this->m_header_valid = obj.m_header_valid;
  this->m_header_spare = obj.m_header_spare;
  this->m_control_enable = obj.m_control_enable;
  this->m_control_mode = obj.m_control_mode;
  this->m_control_priority = obj.m_control_priority;
  this->m_control_reserved = obj.m_control_reserved;
  return *this;
}

bool MixedStruct ::
  operator==(const MixedStruct& obj) const
{
  return (
    (this->m_header_version == obj.m_header_version) &&
    (this->m_header_type == obj.m_header_type) &&
    (this->m_header_valid == obj.m_header_valid) &&
    (this->m_header_spare == obj.m_header_spare) &&
    (this->m_counter == obj.m_counter) &&
    (this->m_control_enable == obj.m_control_enable) &&
    (this->m_control_mode == obj.m_control_mode) &&
    (this->m_control_priority == obj.m_control_priority) &&
    (this->m_control_reserved == obj.m_control_reserved) &&
    (this->m_value == obj.m_value)
  );
}

bool MixedStruct ::
  operator!=(const MixedStruct& obj) const
{
  return !(*this == obj);
}

// ----------------------------------------------------------------------
// Member functions
// ----------------------------------------------------------------------

Fw::SerializeStatus MixedStruct ::
  serializeTo(Fw::SerializeBufferBase& buffer, Fw::Serialization::Endianness mode) const
{
  Fw::SerializeStatus status;

  U8 packed_header = 0;

  packed_header |= (this->m_header_version & 0x7) << 0;

  packed_header |= (this->m_header_type & 0x7) << 3;

  packed_header |= (this->m_header_valid & 0x1) << 6;

  packed_header |= (this->m_header_spare & 0x1) << 7;
  status = buffer.serializeFrom(packed_header, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  status = buffer.serializeFrom(this->m_counter, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  U16 packed_control = 0;

  packed_control |= (this->m_control_enable & 0x1) << 0;

  packed_control |= (this->m_control_mode & 0x7) << 1;

  packed_control |= (this->m_control_priority & 0xf) << 4;

  packed_control |= (this->m_control_reserved & 0xff) << 8;
  status = buffer.serializeFrom(packed_control, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  status = buffer.serializeFrom(this->m_value, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  return status;
}

Fw::SerializeStatus MixedStruct ::
  deserializeFrom(Fw::SerializeBufferBase& buffer, Fw::Serialization::Endianness mode)
{
  Fw::SerializeStatus status;

  U8 packed_header;
  status = buffer.deserializeTo(packed_header, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  this->m_header_version = (packed_header >> 0) & 0x7;

  this->m_header_type = (packed_header >> 3) & 0x7;

  this->m_header_valid = (packed_header >> 6) & 0x1;

  this->m_header_spare = (packed_header >> 7) & 0x1;

  status = buffer.deserializeTo(this->m_counter, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  U16 packed_control;
  status = buffer.deserializeTo(packed_control, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  this->m_control_enable = (packed_control >> 0) & 0x1;

  this->m_control_mode = (packed_control >> 1) & 0x7;

  this->m_control_priority = (packed_control >> 4) & 0xf;

  this->m_control_reserved = (packed_control >> 8) & 0xff;

  status = buffer.deserializeTo(this->m_value, mode);
  if (status != Fw::FW_SERIALIZE_OK) {
    return status;
  }

  return status;
}

#if FW_SERIALIZABLE_TO_STRING

void MixedStruct ::
  toString(Fw::StringBase& sb) const
{
  Fw::String tmp;
  sb = "( ";
  tmp.format("%hhu", this->m_header_version);
  sb += tmp;
  sb += ", ";
  tmp.format("%hhu", this->m_header_type);
  sb += tmp;
  sb += ", ";
  tmp.format("%hhu", this->m_header_valid);
  sb += tmp;
  sb += ", ";
  tmp.format("%hhu", this->m_header_spare);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_counter);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_control_enable);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_control_mode);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_control_priority);
  sb += tmp;
  sb += ", ";
  tmp.format("%hu", this->m_control_reserved);
  sb += tmp;
  sb += ", ";
  tmp.format("%f", this->m_value);
  sb += tmp;
  sb += " )";
}

#endif

// ----------------------------------------------------------------------
// Setter functions
// ----------------------------------------------------------------------

void MixedStruct ::
  set_header_version(U8 value)
{
  this->m_header_version = value & 0x7;
}

void MixedStruct ::
  set_header_type(U8 value)
{
  this->m_header_type = value & 0x7;
}

void MixedStruct ::
  set_header_valid(U8 value)
{
  this->m_header_valid = value & 0x1;
}

void MixedStruct ::
  set_header_spare(U8 value)
{
  this->m_header_spare = value & 0x1;
}

void MixedStruct ::
  set_counter(U16 counter)
{
  this->m_counter = counter;
}

void MixedStruct ::
  set_control_enable(U16 value)
{
  this->m_control_enable = value & 0x1;
}

void MixedStruct ::
  set_control_mode(U16 value)
{
  this->m_control_mode = value & 0x7;
}

void MixedStruct ::
  set_control_priority(U16 value)
{
  this->m_control_priority = value & 0xf;
}

void MixedStruct ::
  set_control_reserved(U16 value)
{
  this->m_control_reserved = value & 0xff;
}

void MixedStruct ::
  set_value(F32 value)
{
  this->m_value = value;
}

void MixedStruct ::
  set(U16 counter, F32 value)
{
  this->m_counter = counter;
  this->m_value = value;
}
