#!/bin/sh

. ../../../../scripts/test-utils.sh

cpp_doc_ok()
{
  gcc -c C.cpp Other.cpp
}

tests="
cpp_doc_ok
"

echo 'generating C++ with the project Scala version'
if ! (cd ../../../.. && ./fpp-sbt --batch \
  'lib/Test/runMain generateCppDoc lib/test/codegen/CppWriter') \
  > build_log.txt 2>&1
then
  echo 'Scala compilation or C++ generation failed'
  echo 'see build_log.txt' for details
  exit 1
fi

run_suite $tests
