#!/bin/sh -e

# ----------------------------------------------------------------------
# FPP installer
# ----------------------------------------------------------------------
# To select a version of java other than the system default,
# set the environment variable
# FPP_JAVA_HOME
#
# To pass flags to sbt, set the environment variable
# FPP_SBT_FLAGS
#
# To pass flags to java, set the environment variable
# FPP_JAVA_FLAGS
# ----------------------------------------------------------------------

# Check arguments
usage()
{
  echo 'usage: install [--scala-native] [dest-dir]' 1>&2
  exit 1
}

mode=jvm
dest_arg=
for arg in "$@"
do
  case "$arg" in
    --scala-native)
      test "$mode" = jvm || usage
      mode=scala-native
      ;;
    -*) usage ;;
    *)
      test -z "$dest_arg" || usage
      dest_arg=$arg
      ;;
  esac
done

# Check for output directory
if test -n "$dest_arg"
then
  # Convert to absolute path as the `cd` to 'compiler' will break relative paths passed in
  mkdir -p "$dest_arg"
  dest=`cd "$dest_arg"; pwd`
else
  dest=bin
fi

# Go to the working directory, so that relative paths work as expected
wd=`dirname $0`
cd $wd

# Pull in the version info
. ../version.sh

if test -n "$FPP_JAVA_HOME"
then
  sbt="sbt --java-home $FPP_JAVA_HOME $FPP_SBT_FLAGS"
  java="$FPP_JAVA_HOME/bin/java $FPP_JAVA_FLAGS"
else
  sbt="sbt $FPP_SBT_FLAGS"
  java=java $FPP_JAVA_FLAGS
fi
echo "sbt command: $sbt"
if test "$mode" = jvm
then
  echo "java command: $java"
fi

dir=`dirname $dest`
dir=`cd $dir; pwd`
base=`basename $dest`
dest=$dir/$base

tools=`cat ./tools.txt`

if git describe --tags --always > /dev/null 2>&1
then
  # Ask git for the current version, if it is available
  version=`git describe --tags --always`
else
  # Otherwise use the hard-coded version
  version="$VERSION"
fi
util=lib/src/main/scala/util
echo "Updating version to $version"
sed -i.update.bak -e "s/val v = .*/val v = \"$version\"/" \
  $util/Version.scala

restore_version()
{
  echo "Restoring Version.scala"
  sed -i.restore.bak -e 's/val v = .*/val v = "[unknown version]"/' \
    $util/Version.scala
}
trap restore_version 0 1 2 15

if test "$mode" = scala-native
then
  echo "Building Scala Native executable"
  cmd="$sbt nativeFpp/nativeLink"
else
  echo "Building jar files"
  cmd="$sbt assembly"
fi
echo "$cmd"
$cmd

restore_version
trap - 0 1 2 15

mkdir -p $dest

echo "Installing fpp at $dest"
if test "$mode" = scala-native
then
  native_binary=`find tools/fpp/target-native -type f \( -name fpp -o -name fpp-out \) -print -quit`
  if test -z "$native_binary"
  then
    echo 'Scala Native build produced no fpp executable' 1>&2
    exit 1
  fi
  echo "  $native_binary"
  install -m 755 "$native_binary" "$dest/fpp"
  tool_command='"`dirname $0`/fpp"'
else
  jars=`find tools/fpp/target -type f -name '*assembly*.jar'`
  if test -z "$jars"
  then
    echo 'JVM build produced no assembly jar' 1>&2
    exit 1
  fi
  jar=$(ls -t $jars | sed -n '1p')
  echo "  $jar"
  cp "$jar" "$dest/fpp.jar"
  echo '#!/bin/sh
'$java' -jar "`dirname $0`/'fpp'.jar" "$@"' > "$dest/fpp"
  chmod +x "$dest/fpp"
  tool_command="$java -jar \"\`dirname \$0\`/fpp.jar\""
fi

echo "Installing tools at $dest"
for tool in $tools
do
  printf '#!/bin/sh\n%s %s "$@"\n' "$tool_command" "$tool" > "$dest/fpp-$tool"
  chmod +x "$dest/fpp-$tool"
done
